FROM php:8.0-cli-bullseye AS BUILDER

COPY appserve-0.1.0.tar.gz /usr/src/appserve.tar.gz

RUN set -ex \
    && apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y ca-certificates build-essential libssl-dev libpcre2-dev \
    && mkdir -p /usr/lib/appserve/modules /usr/lib/appserve/debug-modules /usr/src/appserve \
    && tar -xzf /usr/src/appserve.tar.gz -C /usr/src/appserve \
    && cd /usr/src/appserve \
    && NCPU="$(getconf _NPROCESSORS_ONLN)" \
    && DEB_HOST_MULTIARCH="$(dpkg-architecture -q DEB_HOST_MULTIARCH)" \
    && CC_OPT="$(DEB_BUILD_MAINT_OPTIONS="hardening=+all,-pie" DEB_CFLAGS_MAINT_APPEND="-Wp,-D_FORTIFY_SOURCE=2 -fPIC" dpkg-buildflags --get CFLAGS)" \
    && LD_OPT="$(DEB_BUILD_MAINT_OPTIONS="hardening=+all,-pie" DEB_LDFLAGS_MAINT_APPEND="-Wl,--as-needed -pie" dpkg-buildflags --get LDFLAGS)" \
    && CONFIGURE_ARGS="--prefix=/usr \
                --state=/var/lib/appserve \
                --control=unix:/var/run/control.appserve.sock \
                --pid=/var/run/appserve.pid \
                --log=/var/log/appserve.log \
                --tmp=/var/tmp \
                --user=appserve \
                --group=appserve \
                --openssl \
                --libdir=/usr/lib/$DEB_HOST_MULTIARCH" \
    && ./configure $CONFIGURE_ARGS --cc-opt="$CC_OPT" --ld-opt="$LD_OPT" --modules=/usr/lib/appserve/debug-modules --debug \
    && make -j $NCPU appserved \
    && install -pm755 build/appserved /usr/sbin/appserved-debug \
    && make clean \
    && ./configure $CONFIGURE_ARGS --cc-opt="$CC_OPT" --ld-opt="$LD_OPT" --modules=/usr/lib/appserve/modules \
    && make -j $NCPU appserved \
    && install -pm755 build/appserved /usr/sbin/appserved \
    && make clean \
    && ./configure $CONFIGURE_ARGS --cc-opt="$CC_OPT" --modules=/usr/lib/appserve/debug-modules --debug \
    && ./configure php \
    && make -j $NCPU php-install \
    && make clean \
    && ./configure $CONFIGURE_ARGS --cc-opt="$CC_OPT" --modules=/usr/lib/appserve/modules \
    && ./configure php \
    && make -j $NCPU php-install \
    && ldd /usr/sbin/appserved | awk '/=>/{print $(NF-1)}' | while read n; do dpkg-query -S $n; done | sed 's/^\([^:]\+\):.*$/\1/' | sort | uniq > /requirements.apt

FROM php:8.0-cli-bullseye
LABEL org.opencontainers.image.title="AppServe"
LABEL org.opencontainers.image.description="AppServe application server for Docker."
LABEL org.opencontainers.image.url="https://github.com/hongzhidao/AppServe"
LABEL org.opencontainers.image.source="https://github.com/hongzhidao/AppServe"
LABEL org.opencontainers.image.documentation="https://github.com/hongzhidao/AppServe/blob/main/docs/migration.md"
LABEL org.opencontainers.image.vendor="Zhidao HONG"
LABEL org.opencontainers.image.version="0.1.0"
COPY docker-entrypoint.sh /usr/local/bin/
COPY --from=BUILDER /usr/sbin/appserved /usr/sbin/appserved
COPY --from=BUILDER /usr/sbin/appserved-debug /usr/sbin/appserved-debug
COPY --from=BUILDER /usr/lib/appserve/ /usr/lib/appserve/
COPY --from=BUILDER /requirements.apt /requirements.apt
RUN ldconfig
RUN set -x \
    && mkdir -p /var/lib/appserve/ \
    && mkdir -p /docker-entrypoint.d/ \
    && groupadd --gid 999 appserve \
    && useradd \
         --uid 999 \
         --gid appserve \
         --no-create-home \
         --home /nonexistent \
         --comment "appserve user" \
         --shell /bin/false \
         appserve \
    && apt update \
    && apt --no-install-recommends --no-install-suggests -y install curl $(cat /requirements.apt) \
    && rm -rf /var/lib/apt/lists/* \
    && rm -f /requirements.apt \
    && ln -sf /dev/stderr /var/log/appserve.log

STOPSIGNAL SIGTERM

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

CMD ["appserved", "--no-daemon", "--control", "unix:/var/run/control.appserve.sock"]
