MODULES+=			python36
MODULE_SUFFIX_python36=		python3.6

MODULE_SUMMARY_python36=	Python 3.6 module for AppServe

MODULE_VERSION_python36=	$(VERSION)
MODULE_RELEASE_python36=	1

MODULE_CONFARGS_python36=	python --config=python3.6-config
MODULE_MAKEARGS_python36=	python3.6
MODULE_INSTARGS_python36=	python3.6-install

MODULE_SOURCES_python36=	unit.example-python-app \
				unit.example-python3.6-config

BUILD_DEPENDS_python36=	python3.6-dev
BUILD_DEPENDS+=		$(BUILD_DEPENDS_python36)

MODULE_BUILD_DEPENDS_python36=,python3.6-dev

define MODULE_PREINSTALL_python36
	mkdir -p debian/appserve-python3.6/usr/share/doc/appserve-python3.6/examples/python-app
	install -m 644 -p debian/unit.example-python-app debian/appserve-python3.6/usr/share/doc/appserve-python3.6/examples/python-app/wsgi.py
	install -m 644 -p debian/unit.example-python3.6-config debian/appserve-python3.6/usr/share/doc/appserve-python3.6/examples/appserve.config
endef
export MODULE_PREINSTALL_python36

define MODULE_POST_python36
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python36) has been installed.

To check out the sample app, run these commands:

 sudo service appserve restart
 cd /usr/share/doc/appserve-$(MODULE_SUFFIX_python36)/examples
 sudo curl -X PUT --data-binary @appserve.config --unix-socket /var/run/control.appserve.sock http://localhost/config
 curl http://localhost:8400/

Project repository (currently private): https://github.com/hongzhidao/AppServe

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python36
