MODULES+=			python310
MODULE_SUFFIX_python310=		python3.10

MODULE_SUMMARY_python310=	Python 3.10 module for AppServe

MODULE_VERSION_python310=	$(VERSION)
MODULE_RELEASE_python310=	1

MODULE_CONFARGS_python310=	python --config=python3.10-config
MODULE_MAKEARGS_python310=	python3.10
MODULE_INSTARGS_python310=	python3.10-install

MODULE_SOURCES_python310=	unit.example-python-app \
				unit.example-python3.10-config

BUILD_DEPENDS_python310=	python3.10-dev
BUILD_DEPENDS+=		$(BUILD_DEPENDS_python310)

MODULE_BUILD_DEPENDS_python310=,python3.10-dev

define MODULE_PREINSTALL_python310
	mkdir -p debian/appserve-python3.10/usr/share/doc/appserve-python3.10/examples/python-app
	install -m 644 -p debian/unit.example-python-app debian/appserve-python3.10/usr/share/doc/appserve-python3.10/examples/python-app/wsgi.py
	install -m 644 -p debian/unit.example-python3.10-config debian/appserve-python3.10/usr/share/doc/appserve-python3.10/examples/appserve.config
endef
export MODULE_PREINSTALL_python310

define MODULE_POST_python310
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python310) has been installed.

To check out the sample app, run these commands:

 sudo service appserve restart
 cd /usr/share/doc/appserve-$(MODULE_SUFFIX_python310)/examples
 sudo curl -X PUT --data-binary @appserve.config --unix-socket /var/run/control.appserve.sock http://localhost/config
 curl http://localhost:8400/

Project repository: https://github.com/hongzhidao/AppServe

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python310
