MODULES+=		jsc16
MODULE_SUFFIX_jsc16=	jsc16

MODULE_SUMMARY_jsc16=	Java 16 module for AppServe

MODULE_VERSION_jsc16=	$(VERSION)
MODULE_RELEASE_jsc16=	1

MODULE_CONFARGS_jsc16=	java --module=java16 --home=/usr/lib/jvm/java-16-openjdk-$$\(DEB_HOST_ARCH\) --jars=/usr/share/appserve-jsc-common/
MODULE_MAKEARGS_jsc16=	java16
MODULE_INSTARGS_jsc16=	java16-install

MODULE_SOURCES_jsc16=	unit.example-jsc-app \
			unit.example-jsc16-config

BUILD_DEPENDS_jsc16=	openjdk-16-jdk-headless openjdk-16-jre-headless
BUILD_DEPENDS+=		$(BUILD_DEPENDS_jsc16)

MODULE_BUILD_DEPENDS_jsc16=,openjdk-16-jdk-headless
MODULE_DEPENDS_jsc16=,openjdk-16-jre-headless,appserve-jsc-common (= $(MODULE_VERSION_jsc_common)-$(MODULE_RELEASE_jsc_common)~$(CODENAME))

define MODULE_PREINSTALL_jsc16
	mkdir -p debian/appserve-jsc16/usr/share/doc/appserve-jsc16/examples/jsc-app
	install -m 644 -p debian/unit.example-jsc-app debian/appserve-jsc16/usr/share/doc/appserve-jsc16/examples/jsc-app/index.jsp
	install -m 644 -p debian/unit.example-jsc16-config debian/appserve-jsc16/usr/share/doc/appserve-jsc16/examples/appserve.config
	install -m 644 -p src/java/README.JSR-340 debian/appserve-jsc16/usr/share/doc/appserve-jsc16/
endef
export MODULE_PREINSTALL_jsc16

define MODULE_POSTINSTALL_jsc16
	cd $$\(BUILDDIR_unit\) \&\& \
        DESTDIR=$$\(INSTALLDIR\) make java-shared-uninstall
endef
export MODULE_POSTINSTALL_jsc16

define MODULE_POST_jsc16
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_jsc16) has been installed.

To check out the sample app, run these commands:

 sudo service appserve restart
 cd /usr/share/doc/appserve-$(MODULE_SUFFIX_jsc16)/examples
 sudo curl -X PUT --data-binary @appserve.config --unix-socket /var/run/control.appserve.sock http://localhost/config
 curl http://localhost:8800/

Project repository (currently private): https://github.com/hongzhidao/AppServe

NOTICE:

This version of Unit code is made available in support of the open source
development process.  This is an intermediate build made available for
testing purposes only.  This Unit code is untested and presumed incompatible
with the JSR 340 Java Servlet 3.1 specification.  You should not deploy or
write to this code.  You should instead deploy and write production
applications on pre-built binaries that have been tested and certified
to meet the JSR-340 compatibility requirements such as certified binaries
published for the JSR-340 reference implementation available at
https://javaee.github.io/glassfish/.

Redistribution of any Intermediate Build must retain this notice.

Oracle and Java are registered trademarks of Oracle and/or its affiliates.
Other names may be trademarks of their respective owners.

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_jsc16
