MODULES+=		python
MODULE_SUFFIX_python=	python

MODULE_SUMMARY_python=	Python module for AppServe

MODULE_VERSION_python=	$(VERSION)
MODULE_RELEASE_python=	1

MODULE_CONFARGS_python=	python
MODULE_MAKEARGS_python=	python
MODULE_INSTARGS_python=	python-install

MODULE_SOURCES_python=	unit.example-python-app \
			unit.example-python-config

BUILD_DEPENDS_python=	python-dev
BUILD_DEPENDS+=		$(BUILD_DEPENDS_python)

MODULE_BUILD_DEPENDS_python=,python-dev

define MODULE_PREINSTALL_python
	mkdir -p debian/appserve-python/usr/share/doc/appserve-python/examples/python-app
	install -m 644 -p debian/unit.example-python-app debian/appserve-python/usr/share/doc/appserve-python/examples/python-app/wsgi.py
	install -m 644 -p debian/unit.example-python-config debian/appserve-python/usr/share/doc/appserve-python/examples/appserve.config
endef
export MODULE_PREINSTALL_python

define MODULE_POST_python
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python) has been installed.

To check out the sample app, run these commands:

 sudo service appserve restart
 cd /usr/share/doc/appserve-$(MODULE_SUFFIX_python)/examples
 sudo curl -X PUT --data-binary @appserve.config --unix-socket /var/run/control.appserve.sock http://localhost/config
 curl http://localhost:8400/

Project repository: https://github.com/hongzhidao/AppServe

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python
