MODULES+=			python37
MODULE_SUFFIX_python37=		python3.7

MODULE_SUMMARY_python37=	Python 3.7 module for AppServe

MODULE_VERSION_python37=	$(VERSION)
MODULE_RELEASE_python37=	1

MODULE_CONFARGS_python37=	python --config=python3.7-config
MODULE_MAKEARGS_python37=	python3.7
MODULE_INSTARGS_python37=	python3.7-install

MODULE_SOURCES_python37=	unit.example-python-app \
				unit.example-python3.7-config

BUILD_DEPENDS_python37=	python3.7-dev
BUILD_DEPENDS+=		$(BUILD_DEPENDS_python37)

MODULE_BUILD_DEPENDS_python37=,python3.7-dev

define MODULE_PREINSTALL_python37
	mkdir -p debian/appserve-python3.7/usr/share/doc/appserve-python3.7/examples/python-app
	install -m 644 -p debian/unit.example-python-app debian/appserve-python3.7/usr/share/doc/appserve-python3.7/examples/python-app/wsgi.py
	install -m 644 -p debian/unit.example-python3.7-config debian/appserve-python3.7/usr/share/doc/appserve-python3.7/examples/appserve.config
endef
export MODULE_PREINSTALL_python37

define MODULE_POST_python37
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python37) has been installed.

To check out the sample app, run these commands:

 sudo service appserve restart
 cd /usr/share/doc/appserve-$(MODULE_SUFFIX_python37)/examples
 sudo curl -X PUT --data-binary @appserve.config --unix-socket /var/run/control.appserve.sock http://localhost/config
 curl http://localhost:8400/

Project repository (currently private): https://github.com/hongzhidao/AppServe

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python37
