MODULES+=			python35
MODULE_SUFFIX_python35=		python3.5

MODULE_SUMMARY_python35=	Python 3.5 module for AppServe

MODULE_VERSION_python35=	$(VERSION)
MODULE_RELEASE_python35=	1

MODULE_CONFARGS_python35=	python --config=python3.5-config
MODULE_MAKEARGS_python35=	python3.5
MODULE_INSTARGS_python35=	python3.5-install

MODULE_SOURCES_python35=	unit.example-python-app \
				unit.example-python3.5-config

BUILD_DEPENDS_python35=	python3.5-dev
BUILD_DEPENDS+=		$(BUILD_DEPENDS_python35)

MODULE_BUILD_DEPENDS_python35=,python3.5-dev

define MODULE_PREINSTALL_python35
	mkdir -p debian/appserve-python3.5/usr/share/doc/appserve-python3.5/examples/python-app
	install -m 644 -p debian/unit.example-python-app debian/appserve-python3.5/usr/share/doc/appserve-python3.5/examples/python-app/wsgi.py
	install -m 644 -p debian/unit.example-python3.5-config debian/appserve-python3.5/usr/share/doc/appserve-python3.5/examples/appserve.config
endef
export MODULE_PREINSTALL_python35

define MODULE_POST_python35
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python35) has been installed.

To check out the sample app, run these commands:

 sudo service appserve restart
 cd /usr/share/doc/appserve-$(MODULE_SUFFIX_python35)/examples
 sudo curl -X PUT --data-binary @appserve.config --unix-socket /var/run/control.appserve.sock http://localhost/config
 curl http://localhost:8400/

Project repository: https://github.com/hongzhidao/AppServe

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python35
