MODULES+=			python39
MODULE_SUFFIX_python39=		python3.9

MODULE_SUMMARY_python39=	Python 3.9 module for AppServe

MODULE_VERSION_python39=	$(VERSION)
MODULE_RELEASE_python39=	1

MODULE_CONFARGS_python39=	python --config=python3.9-config
MODULE_MAKEARGS_python39=	python3.9
MODULE_INSTARGS_python39=	python3.9-install

MODULE_SOURCES_python39=	unit.example-python-app \
				unit.example-python3.9-config

BUILD_DEPENDS_python39=	python3.9-dev
BUILD_DEPENDS+=		$(BUILD_DEPENDS_python39)

MODULE_BUILD_DEPENDS_python39=,python3.9-dev

define MODULE_PREINSTALL_python39
	mkdir -p debian/appserve-python3.9/usr/share/doc/appserve-python3.9/examples/python-app
	install -m 644 -p debian/unit.example-python-app debian/appserve-python3.9/usr/share/doc/appserve-python3.9/examples/python-app/wsgi.py
	install -m 644 -p debian/unit.example-python3.9-config debian/appserve-python3.9/usr/share/doc/appserve-python3.9/examples/appserve.config
endef
export MODULE_PREINSTALL_python39

define MODULE_POST_python39
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python39) has been installed.

To check out the sample app, run these commands:

 sudo service appserve restart
 cd /usr/share/doc/appserve-$(MODULE_SUFFIX_python39)/examples
 sudo curl -X PUT --data-binary @appserve.config --unix-socket /var/run/control.appserve.sock http://localhost/config
 curl http://localhost:8400/

Project repository (currently private): https://github.com/hongzhidao/AppServe

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python39
