MODULES+=		python35
MODULE_SUFFIX_python35=	python3.5

MODULE_SUMMARY_python35=	Python 3.5 module for AppServe

MODULE_VERSION_python35=	$(VERSION)
MODULE_RELEASE_python35=	1

MODULE_CONFARGS_python35=	python --config=python3.5-config
MODULE_MAKEARGS_python35=	python3.5
MODULE_INSTARGS_python35=	python3.5-install

MODULE_SOURCES_python35=	unit.example-python-app \
			unit.example-python35-config

BUILD_DEPENDS_python35=	python35-devel
BUILD_DEPENDS+=		$(BUILD_DEPENDS_python35)

define MODULE_PREINSTALL_python35
%{__mkdir} -p %{buildroot}%{_datadir}/doc/appserve-python35/examples/python-app
%{__install} -m 644 -p %{SOURCE100} \
    %{buildroot}%{_datadir}/doc/appserve-python35/examples/python-app/wsgi.py
%{__install} -m 644 -p %{SOURCE101} \
    %{buildroot}%{_datadir}/doc/appserve-python35/examples/appserve.config
endef
export MODULE_PREINSTALL_python35

define MODULE_FILES_python35
%{_libdir}/appserve/modules/*
%{_libdir}/appserve/debug-modules/*
endef
export MODULE_FILES_python35

define MODULE_POST_python35
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python35) has been installed.

To check the sample app, run these commands:

 sudo service appserve start
 cd /usr/share/doc/%{name}/examples
 sudo curl -X PUT --data-binary @appserve.config --unix-socket /var/run/appserve/control.sock http://localhost/config
 curl http://localhost:8400/

Project repository (currently private): https://github.com/hongzhidao/AppServe

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python35
