MODULES+=		python38
MODULE_SUFFIX_python38=	python3.8

MODULE_SUMMARY_python38=	Python 3.8 module for AppServe

MODULE_VERSION_python38=	$(VERSION)
MODULE_RELEASE_python38=	1

MODULE_CONFARGS_python38=	python --config=python3.8-config
MODULE_MAKEARGS_python38=	python3.8
MODULE_INSTARGS_python38=	python3.8-install

MODULE_SOURCES_python38=	unit.example-python-app \
			unit.example-python38-config

ifneq (,$(findstring $(OSVER),opensuse-tumbleweed sles fedora amazonlinux2))
BUILD_DEPENDS_python38=	python3-devel
else
BUILD_DEPENDS_python38=	python38-devel
endif

BUILD_DEPENDS+=		$(BUILD_DEPENDS_python38)

define MODULE_PREINSTALL_python38
%{__mkdir} -p %{buildroot}%{_datadir}/doc/appserve-python38/examples/python-app
%{__install} -m 644 -p %{SOURCE100} \
    %{buildroot}%{_datadir}/doc/appserve-python38/examples/python-app/wsgi.py
%{__install} -m 644 -p %{SOURCE101} \
    %{buildroot}%{_datadir}/doc/appserve-python38/examples/appserve.config
endef
export MODULE_PREINSTALL_python38

define MODULE_FILES_python38
%{_libdir}/appserve/modules/*
%{_libdir}/appserve/debug-modules/*
endef
export MODULE_FILES_python38

define MODULE_POST_python38
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python38) has been installed.

To check the sample app, run these commands:

 sudo service appserve start
 cd /usr/share/doc/%{name}/examples
 sudo curl -X PUT --data-binary @appserve.config --unix-socket /var/run/appserve/control.sock http://localhost/config
 curl http://localhost:8400/

Project repository: https://github.com/hongzhidao/AppServe

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python38
