MODULES+=		python310
MODULE_SUFFIX_python310=	python3.10

MODULE_SUMMARY_python310=	Python 3.10 module for AppServe

MODULE_VERSION_python310=	$(VERSION)
MODULE_RELEASE_python310=	1

MODULE_CONFARGS_python310=	python --config=python3.10-config
MODULE_MAKEARGS_python310=	python3.10
MODULE_INSTARGS_python310=	python3.10-install

MODULE_SOURCES_python310=	unit.example-python-app \
			unit.example-python310-config

ifneq (,$(findstring $(OSVER),opensuse-tumbleweed sles fedora amazonlinux2))
BUILD_DEPENDS_python310=	python3-devel
else
BUILD_DEPENDS_python310=	python310-devel
endif

BUILD_DEPENDS+=		$(BUILD_DEPENDS_python310)

define MODULE_PREINSTALL_python310
%{__mkdir} -p %{buildroot}%{_datadir}/doc/appserve-python310/examples/python-app
%{__install} -m 644 -p %{SOURCE100} \
    %{buildroot}%{_datadir}/doc/appserve-python310/examples/python-app/wsgi.py
%{__install} -m 644 -p %{SOURCE101} \
    %{buildroot}%{_datadir}/doc/appserve-python310/examples/appserve.config
endef
export MODULE_PREINSTALL_python310

define MODULE_FILES_python310
%{_libdir}/appserve/modules/*
%{_libdir}/appserve/debug-modules/*
endef
export MODULE_FILES_python310

define MODULE_POST_python310
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python310) has been installed.

To check the sample app, run these commands:

 sudo service appserve start
 cd /usr/share/doc/%{name}/examples
 sudo curl -X PUT --data-binary @appserve.config --unix-socket /var/run/appserve/control.sock http://localhost/config
 curl http://localhost:8400/

Project repository: https://github.com/hongzhidao/AppServe

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python310
