MODULES+=		python313
MODULE_SUFFIX_python313=	python3.13

MODULE_SUMMARY_python313=	Python 3.13 module for AppServe

MODULE_VERSION_python313=	$(VERSION)
MODULE_RELEASE_python313=	1

MODULE_CONFARGS_python313=	python --config=python3.13-config
MODULE_MAKEARGS_python313=	python3.13
MODULE_INSTARGS_python313=	python3.13-install

MODULE_SOURCES_python313=	unit.example-python-app \
			unit.example-python313-config

BUILD_DEPENDS_python313=	python3-devel

BUILD_DEPENDS+=		$(BUILD_DEPENDS_python313)

define MODULE_PREINSTALL_python313
%{__mkdir} -p %{buildroot}%{_datadir}/doc/appserve-python313/examples/python-app
%{__install} -m 644 -p %{SOURCE100} \
    %{buildroot}%{_datadir}/doc/appserve-python313/examples/python-app/wsgi.py
%{__install} -m 644 -p %{SOURCE101} \
    %{buildroot}%{_datadir}/doc/appserve-python313/examples/appserve.config
endef
export MODULE_PREINSTALL_python313

define MODULE_FILES_python313
%{_libdir}/appserve/modules/*
%{_libdir}/appserve/debug-modules/*
endef
export MODULE_FILES_python313

define MODULE_POST_python313
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python313) has been installed.

To check the sample app, run these commands:

 sudo service appserve start
 cd /usr/share/doc/%{name}/examples
 sudo curl -X PUT --data-binary @appserve.config --unix-socket /var/run/appserve/control.sock http://localhost/config
 curl http://localhost:8400/

Project repository (currently private): https://github.com/hongzhidao/AppServe

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python313
